### ISSUE TITLE
Impossible de charger les programmes avec '?guignols'

### ISSUE THREAD

**Issue by buroli** [desbma/canalplus#1]
Hello,

En utilisant la commande : 
`canalplus -p '?guignols' player:vlc
j'ai un Unknown program ''?guignols''.
Est-ce parce que dans le premier level, il n' y a pas les guignols ?

Merci.

**Comment by desbma** [comment]
Salut,

Le point d'interrogation en préfixe indique une recherche, et pas un match exact du nom du programme, donc normalement ça devrait marcher. Chez moi la même commande fonctionne.

Je pense que le problème est que les quotes ( `'` ) sont interprétés comme faisant partie de la chaine passée au script.

Tu es sous quel OS ?
Essayes avec des guillemets classiques (`canalplus -p "?guignols" player:vlc`), voir sans (juste `canalplus -p ?guignols player:vlc`) si tu es sous Windows.

**Comment by buroli** [comment]
Hello,

En effet, en retirant les quotes, tout fonctionne nickel.

Merci à toi
