### ISSUE TITLE
Limité à 100 dans le search ?

### ISSUE THREAD

**Issue by buroli** [desbma/canalplus#2]
Hello, 

Lors des recherches par exemple sur ?groland
Je vois qu'on a souvent 100 items comme limite, c'est voulu ?

Merci

**Comment by desbma** [comment]
C'est une limite implicite de l'API XML de Canal+, par exemple pour "groland" seuls 100 résultats sont retournés : http://service.canal-plus.com/video/rest/search/cplus/groland
