### ISSUE TITLE
Problème pour trouver une vidéo

### ISSUE THREAD

**Issue by raphael-alves** [desbma/canalplus#3]
Bonsoir,

Je rencontre un petit problème avec le script. Je souhaiterais télécharger la dernière émission du petit journal, et en utilisant le script je n'arrive qu'a trouver des extraits, pas l'émission en entier. J'ai essayé tout ce que je pouvais mais pas moyen, du coup je me demande s'il n'y a pas un petit bug...

**Comment by desbma** [comment]
Bonsoir,

Pour le petit journal, Canal+ met à disposition à chaque fois à la fois des extraits et l'émission complète.
Pour l’émission d'hier malheureusement particulière, ils n'ont pas mis "le petit journal" dans le titre, donc elle n’apparaît pas si on recherche ces termes.

Par contre, tu peux la trouver avec :
`canalplus -p '?lpj' .` (en 2è)

Sinon, si tu lances sans paramètres, elle devait apparaître hier dans les catégories "Les Emissions Quotidiennes" ou "Divertissement", mais maintenant ça a été remplacé par l’émission d'aujourd'hui.

**Comment by raphael-alves** [comment]
Bonsoir,

Merci beaucoup pour cette réponse je pense qu'en fait je n'avais pas bien compris la manière d'effectuer une recherche.

J'ai du coup pu la télécharger comme ceci : `canalplus -p '?LPJ : génération Bataclan' -m last ~/Vidéos/`.

Le but était de pouvoir la sous-titrer pour des amis à l'étranger, merci donc pour ton programme et ta réponse.
